<a href="https://colab.research.google.com/github/TechinTK/python_dataviz2023/blob/main/HW2/2.5%E0%B8%A5%E0%B9%88%E0%B8%B2%E0%B8%AA%E0%B8%B8%E0%B8%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##HW2 สร้าง LOGO พรรคก้าวไกล

In [230]:
import numpy as np

In [232]:
MFP=8*np.ones((14,24))
MFP[:1,:]=1
MFP[1:2,1:23]=1
MFP[2:3,20:22]=1
MFP[3:4,19:21]=1
MFP[4:5,18:20]=1
MFP[4:5,4:16]=1
MFP[5:6,17:19]=1
MFP[5:6,5:15]=1
MFP[6:7,16:18]=1
MFP[6:7,12:14]=1
MFP[7:8,15:17]=1
MFP[7:8,11:13]=1
MFP[8:9,14:16]=1
MFP[8:9,10:12]=1
MFP[9:10,13:15]=1
MFP[9:10,9:11]=1
MFP[10:11,12:14]=1
MFP[10:11,8:10]=1
MFP[11:12,11:13]=1
MFP[12:13,10:12]=1
MFP[13:14,9:11]=1
print(MFP)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 8.]
 [8. 8. 8. 8. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 1. 1. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.

## HW2.5 เราสร้าง function print logo พรรค ก้าวไกล โดย input พื้นหลังได้

In [233]:
def create_mfp():
    MFP = 8 * np.ones((14, 24), dtype=int)
    MFP[:1, :] = 1
    MFP[1:2, 1:23] = 1
    MFP[2:3, 20:22] = 1
    MFP[3:4, 19:21] = 1
    MFP[4:5, 18:20] = 1
    MFP[4:5, 4:16] = 1
    MFP[5:6, 17:19] = 1
    MFP[5:6, 5:15] = 1
    MFP[6:7, 16:18] = 1
    MFP[6:7, 12:14] = 1
    MFP[7:8, 15:17] = 1
    MFP[7:8, 11:13] = 1
    MFP[8:9, 14:16] = 1
    MFP[8:9, 10:12] = 1
    MFP[9:10, 13:15] = 1
    MFP[9:10, 9:11] = 1
    MFP[10:11, 12:14] = 1
    MFP[10:11, 8:10] = 1
    MFP[11:12, 11:13] = 1
    MFP[12:13, 10:12] = 1
    MFP[13:14, 9:11]
    return MFP

def print_MFP(background=' ',Logo='1'):
    for row in MFP:
        for value in row:
            if value == 8:
                print(background, end=' ')
            else:
                print(Logo, end=' ')
        print()

background = '8'
Logo = '1'
print_MFP(background, Logo)

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
8 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 1 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 1 8 8 8 
8 8 8 8 1 1 1 1 1 1 1 1 1 1 1 1 8 8 1 1 8 8 8 8 
8 8 8 8 8 1 1 1 1 1 1 1 1 1 1 8 8 1 1 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 1 1 8 8 1 1 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 1 1 8 8 1 1 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 1 1 8 8 1 1 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 1 1 8 8 1 1 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 1 1 8 8 1 1 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 1 1 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 1 1 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 1 1 8 8 8 8 8 8 8 8 8 8 8 8 8 
